apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: hpm-client-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: client
    spec:
      containers:
        - command:
            - npm
            - start
          image: gcr.io/everyones-happy/hpm-client
          imagePullPolicy: 'Always'
          name: client
          ports:
            - containerPort: 3000
          resources: {}
          #        volumeMounts:
          #        - mountPath: /usr/src/app/client
          #          name: client-claim0
          workingDir: /usr/src/app/client
      restartPolicy: Always
#      volumes:
#      - name: client-claim0
#        persistentVolumeClaim:
#          claimName: client-claim0
status: {}
