apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: client
  name: hpm-client-service
spec:
  ports:
    - name: '3000'
      port: 8080
      targetPort: 3000
  selector:
    io.kompose.service: client
  type: NodePort
