apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: house-price-map-mongodb
spec:
  volumes:
    - name: house-price-map-mongo-vol
      persistentVolumeClaim:
        claimName: house-price-map-pvc
  containers:
    - image: mongo
      name: container1
      command:
        - mongod
        - '--bind_ip'
        - '0.0.0.0'
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: house-price-map-mongo-vol
          mountPath: /data/db
          subPath: $(POD_NAME)
