apiVersion: v1
kind: Service
metadata:
  labels:
    app: house-price-map-mongodb
  name: house-price-map-mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: house-price-map-mongodb
