apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: hpm-server-deployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
        - image: gcr.io/everyones-happy/hpm-server
          imagePullPolicy: 'Always'
          name: hpm-server-container
          ports:
            - containerPort: 3001
          workingDir: /usr/src/app/server
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-maps-api-key
                  key: GOOGLE_API_KEY
          env:
            - name: MONGO_DB_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb-property-price-db-url
                  key: MONGO_DB_URL
            - name: MONGO_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: house-price-map-config
                  key: MONGODB_URI
      restartPolicy: Always
